### ISSUE TITLE
Is there a way to get the length for result of a path?

### ISSUE THREAD

**Issue by prashantagarwal** [s3u/JSONPath#107]
I have a JSON
```
{
    collection: [{
      prop: {}
    },{
      prop: 2
    }]
}
```
and I have the path as `collection[*].prop@integer()`. I want to know the size of the result, which should be 1 in this case.

**Comment by brettz9** [comment]
Is there some reason you can't just get `length` on the resulting array?

**Comment by prashantagarwal** [comment]
@brettz9 I am using JsonPath in a rule engine. I want to keep my path generic and therefore thought that it would be great if there is a way to do it.

**Comment by brettz9** [comment]
@prashantagarwal : No, we still don't have the expressiveness of XPath (not to mention XQuery), though a PR would be welcome...

**Comment by prashantagarwal** [comment]
@brettz9 Doing something like [this](https://github.com/CacheControl/json-rules-engine/pull/168#issuecomment-549829680) will solve a lot of my use cases.

**Comment by brettz9** [comment]
Though I haven't taken a close look, from a quick overview JSONata looks quite exciting...

**Comment by Firetrip** [comment]
Hello,

why was this issue closed? 
This is quite a downfall, because filtering becomes a lot less powerful without being able to work with the result array afterwards..

**Comment by brettz9** [comment]
The original poster perhaps closed it due to a relative lack of maintenance of this repository and my mentioning JSONata as an interesting looking project.

PRs would be welcome, but see #124 on our wishing to first see proposals be made as part of a standardization process so that different jsonpath implementations do not end up differing so much.
