### ISSUE TITLE
condition on the root

### ISSUE THREAD

**Issue by gsouf** [s3u/JSONPath#118]
Hi,

I have this kind of json:

```js
{
   foo: 'bar',
   baz: 'qux'
}
```

I want to read value of `baz` only if `foo === "bar"`. I can get it to work for array structures, but not at the root.

I tried many things like:

```
$[?(@.foo === "bar")].baz
$?(@.foo === "bar").baz
$.baz[?(@parent.foo === "bar")]
etc..
```

It just looks like we cannot operate any filters on the root element.

**Comment by brettz9** [comment]
Yes, I believe you're right that there is no current core way to achieve this pretty fundamental filtering type (by object)--not only at root but anywhere. I think there may not have been a great need previously since programmers would tend to drill down before or afterward.

The only option you could have--if the engine is under your control (though if it were, I presume you could also add the root inside an array)--would be to use `otherTypeCallback`:

```js
const {JSONPath} = require("jsonpath-plus")

const json = {
   foo: 'bar',
   baz: 'qux'
};

JSONPath({path: '$.@other()', json, otherTypeCallback (value, path, parent, parentPropertyName) {
  return value && value.foo === 'bar';
}});
```

Demo: https://runkit.com/brettz9/5e8c8b95dee34d001c58e0f2

**Comment by gsouf** [comment]
@brettz9 thanks for your answer! Actually I didn't give up and I tried again. And I found a way to achieve it. Not the most easy to understand when reading but at least it works:

```
  $[?(@property === "foo" && @ === "bar")]^.baz
```

I'm closing this one because it's solved for me.

**Comment by brettz9** [comment]
Ahhh--shows how much I know! :) Nice work finding the way!

I just now added a note on the README to highlight this possibility, so it is now hopefully more evident what is possible (though if not, I'm open to doc PRs).
