### ISSUE TITLE
exclude fields

### ISSUE THREAD

**Issue by antonioaltamura** [s3u/JSONPath#76]
This is my object, can query for the whole object but exclude the `template` field?
```
{
            sections:
       [
            {
                name: "part1",
                title: "Part I",
                children: [{
                    name: "1",
                    title: "part1.1",
                    template:"part1.1 template"
                }, {
                    name: "2",
                    title: "part1.2",
                    template:"part1.2 template"
                }]
			},
		{
			name:"part2",
				//...
		}
	]
 }
```

**Comment by brettz9** [comment]
You can't do this with a mere JSONPath expression as JSONPath is not really concerned with transformations of the result.

However, you can query for objects with or without a given property. And, when using `resultType: "all"`, you can use the `parent` and `parentProperty` properties to manipulate the queried object, you can get your result as follows:

```js
var result = JSONPath({resultType:'all', json: obj, path: '$..*[?(@.template)]'});
result.forEach(function (res) {
    delete res.parent[res.parentProperty].template;
});
```

[JSFiddle](https://jsfiddle.net/vb2o40Lm/6/)

Or for a somewhat more efficient way (that lets you manipulate the object during the query rather than after the fact), you can use the `callback`:

```js
var result = JSONPath({resultType:'all', json: obj, path: '$..*[?(@.template)]',
    callback: function (res) {
        delete res.parent[res.parentProperty].template;
    }
});
alert(JSON.stringify(obj, null, '    '));
```

[JSFiddle](https://jsfiddle.net/ams4h4t6/)

Note that JSONPath allows you to work with whatever object you supply, so these changes will affect the original object; if you don't want that behavior, you'll need to supply a clone of your object.

I will close the issue since that should answer the question, but feel free to comment further if you have further need.
