### ISSUE TITLE
How to nest selects

### ISSUE THREAD

**Issue by lazee** [s3u/JSONPath#81]
Hi,

Given a structure like this:

```json
[
  {
    "id": 1,
    "tags": ["foo","bar"]
  },
  {
    "id": 2,
    "tags": ["bar","zot"]
  }
]
```

How can I do a selection that selects the whole object if the tag array contains "foo"?

This way I only get the tags-arrays back:

```
 '$..tags[?(@ === "foo")]'
```

My guess was:

```
'$..[?(@.tags[?(@property === "foo")])]'
````

But that gives me

```
Error in the given query: Lexical error on line 1. Unrecognized text.
...perty === "foo")])]
-----------------------^
```

This is what I want back from the query:

```json
[
  {
    "id": 1,
    "tags": ["foo","bar"]
  }
]
```

Any help would be greatly appreciated.

**Comment by lazee** [comment]
btw: This works if there is only foo in the array

```
'$..[?(@.tags == "foo")]'
```

But not when there is other tags in there.

**Comment by brettz9** [comment]
In case anyone else needed to know how to do this:

`$..[?(@.tags && @.tags.indexOf("foo") > -1)]`

or, assuming a modern browser:

`$..[?(@.tags && @.tags.includes("foo"))]`

https://jsfiddle.net/acka9bpe/1/

Note, however, that if that is your exact structure, it is better not to check all descendants, and specifically just check the root, e.g.:

`$[?(@.tags && @.tags.indexOf("foo") > -1)]`

Or, since you know `tags` will always exist in that context, just:

`$[?(@.tags.indexOf("foo") > -1)]`
