### ISSUE TITLE
Support querying circular objects with guards

### ISSUE THREAD

**Issue by brettz9** [s3u/JSONPath#91]
I think we should support querying circular objects with guards against infinite recursion.

**Comment by doits** [comment]
:+1:

Traversing circular object with guards would be a nice feature, but in the beginning I'd be happy to have a first step to actually be able to query a circular object with simple paths, for example:

```js
$.books[0].title
```

(e.g. no `..` which tries to go down infinitely). This should work with a circular object, but currently it doesn't because of [JSON.stringify](https://github.com/s3u/JSONPath/blob/master/src/jsonpath.js#L69), which throws a `TypeError: cyclic object value (Firefox)`.

Is there any way to fix this, so at least simple paths work on circular objects?

**Comment by brettz9** [comment]
I've added to `master` (168789234737d9fcd2a4ff301b4caffa50bfe3a9) a fix for this which changes our use of global `eval` to `new Function`, allowing for refactoring which avoids `JSON.stringify`.

(FWIW, a couple subtle differences between `Function` and global `eval` are helpfully described at http://perfectionkills.com/global-eval-what-are-the-options/#new_function , though in our case, the first implication helps us as we don't want globals defined, and I have sought to work around the leakage in the second implication, as relatively obscure as it is.)

Closing as this should resolve, though feel free to comment further.

**Comment by doits** [comment]
Thanks!
